# DesertBooker About preview - static site container.
#
# This repository is already Vite build output (there is no package.json,
# lockfile or source here; it is generated by `npm run preview:about` in the
# private product repo). There is therefore nothing to build in a Node stage:
# the files are copied straight into nginx.
#
# If the source is ever added to this repo, put a build stage in front:
#   FROM node:22-alpine AS build
#   WORKDIR /app
#   COPY package*.json ./
#   RUN npm ci
#   COPY . .
#   RUN npm run build
# and change the COPY below to: COPY --from=build /app/dist /usr/share/nginx/html

FROM nginx:1.25-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx-spa.conf /etc/nginx/conf.d/default.conf

COPY index.html robots.txt sitemap.xml /usr/share/nginx/html/
COPY assets/ /usr/share/nginx/html/assets/
COPY privacy-policy/ /usr/share/nginx/html/privacy-policy/
COPY terms-of-service/ /usr/share/nginx/html/terms-of-service/

EXPOSE 80
